/**
 * ESP32 using library https://github.com/pschatzmann/arduino-audio-tools
 *               and   https://github.com/pschatzmann/Maximilian
 * Generates two sine waves and combines them to play on the internal DAC (GPIO 25 and 26) 
 */
 
#include "AudioTools.h"
#include "AudioLibs/MaximilianDSP.h"

AnalogAudioStream out; // audio is sent to the internal DAC

Maximilian maximilian(out);  // audio is generated by Maximilian

maxiOsc sine1,sine2;  // audio oscillators

void setup() {
  Serial.begin(115200);
  //AudioLogger::instance().begin(Serial, AudioLogger::Info);

  // setup Aduio output
  auto cfg = out.defaultConfig(TX_MODE);
  out.begin(cfg);
  maximilian.begin(cfg);
}

void play(float *output) {
    // output[0] is the left output. output[1] is the right output
    // output is a dual mono North America DTMF dialtone (same audio in left and right)
    // a dialtone is created by combining a 350 Hz and 440 Hz sine wave
    // each waveform is scaled down to 20% of original amplitude to help control level
    output[0]=sine1.sinewave(440)*0.2 + sine2.sinewave(350)*0.2;
    output[1]=output[0];
}


void loop() {
    maximilian.copy();  // perform tasks to generate and send audio out
}
